//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardDesigner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Set_Runtime_PlotInterval {
            get {
                return ((int)(this["Set_Runtime_PlotInterval"]));
            }
            set {
                this["Set_Runtime_PlotInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Set_Runtime_AutoMaximize {
            get {
                return ((bool)(this["Set_Runtime_AutoMaximize"]));
            }
            set {
                this["Set_Runtime_AutoMaximize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Set_Runtime_AutoFullscreen {
            get {
                return ((bool)(this["Set_Runtime_AutoFullscreen"]));
            }
            set {
                this["Set_Runtime_AutoFullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Set_Startup_AutoOpenFile {
            get {
                return ((string)(this["Set_Startup_AutoOpenFile"]));
            }
            set {
                this["Set_Startup_AutoOpenFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Set_Startup_AutoActivate {
            get {
                return ((bool)(this["Set_Startup_AutoActivate"]));
            }
            set {
                this["Set_Startup_AutoActivate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Set_FBStorage_Path {
            get {
                return ((string)(this["Set_FBStorage_Path"]));
            }
            set {
                this["Set_FBStorage_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Set_FBStorage_FBPath {
            get {
                return ((string)(this["Set_FBStorage_FBPath"]));
            }
            set {
                this["Set_FBStorage_FBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Set_FBStorage_FBSecret {
            get {
                return ((string)(this["Set_FBStorage_FBSecret"]));
            }
            set {
                this["Set_FBStorage_FBSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Set_CSV_Separator {
            get {
                return ((string)(this["Set_CSV_Separator"]));
            }
            set {
                this["Set_CSV_Separator"] = value;
            }
        }
    }
}
